name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config openjdk-17-jdk unzip

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
