name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython==0.29.33
          pip install python-for-android==2024.01.21

      - name: Build APK
        run: |
          buildozer android debug
