name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython==0.29.33
        pip install buildozer==1.5.0

    - name: Install Android SDK & AIDL tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk unzip wget
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $HOME/android-sdk
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" "platforms;android-31" "build-tools;31.0.0"

        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Build APK
      run: buildozer android debug
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        PATH: ${{ env.PATH }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mi-apk
        path: bin/*.apk
