name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Buildozer global data
        uses: actions/cache@v2
        with:
          path: .buildozer-global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache project Buildozer files
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: buildozer-local-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: |
            export JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
            yes | buildozer -v android debug
          buildozer_version: stable
          workdir: .

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-app-kivy-apk
          path: ${{ steps.buildozer.outputs.filename }}
