name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools \
            libtool libffi-dev libssl-dev \
            libsqlite3-dev zlib1g-dev \
            libncurses5 libncurses5-dev \
            libncursesw5 libncursesw5-dev \
            libreadline-dev libgdbm-dev \
            libbz2-dev liblzma-dev

          pip install --upgrade pip setuptools Cython virtualenv
          pip install buildozer==1.5.0

      - name: Set up Android SDK
        env:
          ANDROID_SDK_ROOT: /home/runner/android-sdk
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip -d cmdline-tools
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/

      - name: Accept licenses and install build tools
        env:
          ANDROID_SDK_ROOT: /home/runner/android-sdk
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      - name: Build APK
        env:
          ANDROIDSDK: /home/runner/android-sdk
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/*.apk
