name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev libxml2-dev libxslt-dev zlib1g-dev pkg-config libncurses5 libncurses5-dev libsqlite3-dev
        pip install --upgrade pip
        pip install cython
        pip install buildozer==1.5.0

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: miapp.apk
        path: bin/*.apk
